### ISSUE TITLE
Building error: 'device not found,exiting roomservice'

### ISSUE THREAD

**Issue by manu-palmero** [minimal-manifest-twrp/platform_manifest_twrp_omni#111]
I tried to compile TWRP for a Galaxy A24, the device tree is fine, but when I type the lunch command, I get this:

```
$ . build/envsetup.sh 
including device/samsung/a24/vendorsetup.sh
including vendor/omni/vendorsetup.sh
including sdk/bash_completion/adb.bash

$ lunch
You're building on Linux

Lunch menu... pick a combo:
     1. aosp_arm-eng
     2. aosp_arm64-eng
     3. aosp_mips-eng
     4. aosp_mips64-eng
     5. aosp_x86-eng
     6. aosp_x86_64-eng
     7. omni_a24-user
     8. omni_a24-userdebug
     9. omni_a24-eng
     10. omni_emulator-userdebug

Which would you like? [aosp_arm-eng] 9
WARNING: Trying to fetch a device that's already there
Traceback (most recent call last):
  File "/media/manu/Datos/Celulares/A24/TWRP/minimal-manifest-omni/vendor/omni/build/tools/roomservice.py", line 405, in <module>
    fetch_device(device)
  File "/media/manu/Datos/Celulares/A24/TWRP/minimal-manifest-omni/vendor/omni/build/tools/roomservice.py", line 373, in fetch_device
    git_data = search_gerrit_for_device(device)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/manu/Datos/Celulares/A24/TWRP/minimal-manifest-omni/vendor/omni/build/tools/roomservice.py", line 81, in search_gerrit_for_device
    device_data = check_repo_exists(git_data, device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/manu/Datos/Celulares/A24/TWRP/minimal-manifest-omni/vendor/omni/build/tools/roomservice.py", line 57, in check_repo_exists
    raise Exception("{device} not found,"
Exception: a24 not found,exiting roomservice

** Don't have a product spec for: 'omni_a24'
** Do you have the right repo manifest?
```

**Comment by CaptainThrowback** [comment]
You haven't provided a device tree link or even mentioned what manifest branch you're using. I suspect this isn't a manifest issue but a device tree issue, despite your claim that it's not the problem.

**Comment by smsimeonov** [comment]
Wanted to mention I get the same error on a device tree obtained via twrpdtgen.
The tree works just fine with the twrp_11 and twrp_12.1 branches, but those apparently don't work on my device since I'm left with fastboot only. I assume since its a chinese unit, the Android version initially it was built again was 9 or lower. 
I cannot build against twrp_9, however, because of this error.
