### ISSUE TITLE
Problema at creation of twrp image

### ISSUE THREAD

**Issue by Ruby90000** [minimal-manifest-twrp/platform_manifest_twrp_omni#114]
When I try to assembly the twrp image(5.1) for my Lenovo Tab3 7 Essential (TB3-710I) with the device tree generated by twrpdgen, I get the errore "not found repo manifest for "omni_TB3" excluding the other part of the name due to the hyphen. I wait advice.

**Comment by Ruby90000** [comment]
ruby90@Ruby:~$ . build/envsetup.sh
including device/lenovo/TB3710I/vendorsetup.sh
ruby90@Ruby:~$ lunch

You're building on Linux

Lunch menu... pick a combo:
     1. aosp_arm-eng
     2. aosp_arm64-eng
     3. aosp_mips-eng
     4. aosp_mips64-eng
     5. aosp_x86-eng
     6. aosp_x86_64-eng
     7. omni_TB3-710I-userdebug
     8. omni_TB3-710I-eng

Which would you like? [aosp_arm-eng] 7
build/core/product_config.mk:222: *** Can not locate config makefile for product "omni_TB3".  Stop.
Your device can't be found in device sources..
Traceback (most recent call last):
  File "build/tools/roomservice.py", line 296, in <module>
    fetch_device(device)
  File "build/tools/roomservice.py", line 265, in fetch_device
    git_data = search_gerrit_for_device(device)
  File "build/tools/roomservice.py", line 78, in search_gerrit_for_device
    device_data = check_repo_exists(git_data, device)
  File "build/tools/roomservice.py", line 58, in check_repo_exists
    "exiting roomservice".format(device=device))
Exception: TB3 not found,exiting roomservice
build/core/product_config.mk:222: *** Can not locate config makefile for product "omni_TB3".  Stop.

** Don't have a product spec for: 'omni_TB3'
** Do you have the right repo manifest?

** Invalid variant: '710I-userdebug'
** Must be one of user userdebug eng


here is what I am told.

**Comment by lopestom** [comment]
> 7. omni_TB3-710I-userdebug
> 8. omni_TB3-710I-eng

Change names in DT to omni_TB3_710I because source not accept `-` in the name omni_TB3-710I
